_core:
  default_config_hash: ijfbzDTN4CbE7Sr-6ubWzy_t1vH4OtU1doNCLssVz-4
langcode: en
uuid: 9492206e-79c0-45f0-a970-84ab3efd74a8
name: 'Movie Portal'
mail: sandip.poddar@innoraft.com
slogan: ''
page:
  403: ''
  404: ''
  front: /node/18
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: null
